-- MySQL Script generated by MySQL Workbench
-- 06/13/17 10:42:07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proyecto` ;

-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyecto` DEFAULT CHARACTER SET utf8 ;
USE `proyecto` ;

-- -----------------------------------------------------
-- Table `proyecto`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`usuario` (
  `i_id_usuario` INT NOT NULL AUTO_INCREMENT,
  `s_email` VARCHAR(40) NOT NULL,
  `s_password` VARCHAR(70) NULL,
  `s_nombre_completo` VARCHAR(100) NULL,
  `s_telefono` VARCHAR(12) NULL,
  `s_descripcion` VARCHAR(300) NULL,
  `dt_fecha_alta` DATETIME NULL,
  `dt_fecha_baja` DATETIME NULL,
  `b_activo` BIT NULL DEFAULT 1,
  `c_tipo_usuario` CHAR(1) NOT NULL DEFAULT 'E',
  PRIMARY KEY (`i_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`bar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`bar` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`bar` (
  `i_id_bar` INT NOT NULL AUTO_INCREMENT,
  `s_CIF` VARCHAR(10) NOT NULL,
  `s_nombre` VARCHAR(50) NOT NULL,
  `s_direccion_completa` VARCHAR(60) NULL,
  `s_ciudad` VARCHAR(50) NULL,
  `s_provincia` VARCHAR(50) NULL,
  `s_codigo_postal` VARCHAR(5) NULL,
  `s_telefono` VARCHAR(12) NULL,
  `s_email` VARCHAR(40) NULL,
  `dt_fecha_alta` DATETIME NULL,
  `dt_fecha_baja` DATETIME NULL,
  `b_activo` BIT NULL DEFAULT 1,
  PRIMARY KEY (`i_id_bar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`grupo` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`grupo` (
  `i_id_grupo` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(50) NOT NULL,
  `s_descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`i_id_grupo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`pedido` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`pedido` (
  `i_id_pedido` INT NOT NULL AUTO_INCREMENT,
  `dt_fecha_pedido` DATETIME NOT NULL,
  `s_descripcion` VARCHAR(300) NULL,
  `i_id_pedido_conjunto` INT NULL,
  `c_estado` CHAR(1) NOT NULL DEFAULT 'P',
  `i_id_grupo` INT NOT NULL,
  PRIMARY KEY (`i_id_pedido`),
  INDEX `fk_i_id_grupo_idx` (`i_id_grupo` ASC),
  CONSTRAINT `fk_i_id_grupo`
    FOREIGN KEY (`i_id_grupo`)
    REFERENCES `proyecto`.`grupo` (`i_id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`tipo_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`tipo_producto` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`tipo_producto` (
  `i_id_tipo_producto` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(50) NOT NULL,
  `s_descripcion` VARCHAR(300) NULL,
  PRIMARY KEY (`i_id_tipo_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`producto` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`producto` (
  `i_id_producto` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(100) NOT NULL,
  `i_unidades` INT NULL,
  `s_volumen` VARCHAR(30) NULL,
  `s_peso` VARCHAR(30) NULL,
  `dt_fecha_alta` DATETIME NULL,
  `dt_fecha_baja` DATETIME NULL,
  `i_id_tipo_producto` INT NULL,
  `b_activo` BIT NULL DEFAULT 1,
  PRIMARY KEY (`i_id_producto`),
  INDEX `fk_i_id_tipo_producto_idx` (`i_id_tipo_producto` ASC),
  CONSTRAINT `fk_i_id_tipo_producto`
    FOREIGN KEY (`i_id_tipo_producto`)
    REFERENCES `proyecto`.`tipo_producto` (`i_id_tipo_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`linea_pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`linea_pedido` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`linea_pedido` (
  `i_id_linea_pedido` INT NOT NULL AUTO_INCREMENT,
  `i_id_producto` INT NOT NULL,
  `i_unidades` DECIMAL(10,2) NOT NULL,
  `i_id_pedido` INT NOT NULL,
  `i_id_usuario_create` INT NOT NULL,
  `dt_fecha_create` DATETIME NOT NULL,
  `i_id_usuario_update` INT NULL,
  `dt_fecha_update` DATETIME NULL,
  `i_id_bar` INT NOT NULL,
  `i_id_proveedor` INT NOT NULL,
  `precio_compra` DECIMAL(10,2) NULL,
  PRIMARY KEY (`i_id_linea_pedido`),
  INDEX `fk_i_id_producto_idx` (`i_id_producto` ASC),
  INDEX `fk_i_id_pedido_idx` (`i_id_pedido` ASC),
  INDEX `fk_i_id_usuario_idx` (`i_id_usuario_create` ASC),
  CONSTRAINT `fk_i_id_producto`
    FOREIGN KEY (`i_id_producto`)
    REFERENCES `proyecto`.`producto` (`i_id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_pedido`
    FOREIGN KEY (`i_id_pedido`)
    REFERENCES `proyecto`.`pedido` (`i_id_pedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_usuario`
    FOREIGN KEY (`i_id_usuario_create`)
    REFERENCES `proyecto`.`usuario` (`i_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`proveedor` (
  `i_id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(50) NULL,
  `s_descripcion` VARCHAR(300) NULL,
  `s_email` VARCHAR(40) NOT NULL,
  `s_telefono` VARCHAR(12) NULL,
  `dt_fecha_alta` DATETIME NULL,
  `dt_fecha_baja` DATETIME NULL,
  `b_activo` BIT NULL DEFAULT 1,
  `i_id_grupo` INT NOT NULL,
  PRIMARY KEY (`i_id_proveedor`),
  INDEX `fk_i_id_grupo_idx` (`i_id_grupo` ASC),
  CONSTRAINT `fk_i_id_grupo_proveedor`
    FOREIGN KEY (`i_id_grupo`)
    REFERENCES `proyecto`.`grupo` (`i_id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`proveedor_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`proveedor_producto` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`proveedor_producto` (
  `d_precio` DECIMAL(10,2) NOT NULL,
  `s_descripcion` VARCHAR(300) NULL,
  `i_id_proveedor` INT NOT NULL,
  `i_id_producto` INT NOT NULL,
  `b_activo` BIT NULL,
  INDEX `fk_i_id_producto_idx` (`i_id_producto` ASC),
  INDEX `fk_i_id_proveedor_idx` (`i_id_proveedor` ASC),
  PRIMARY KEY (`i_id_proveedor`, `i_id_producto`),
  CONSTRAINT `fk_i_id_producto_proveedor_producto`
    FOREIGN KEY (`i_id_producto`)
    REFERENCES `proyecto`.`producto` (`i_id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_proveedor_proveedor_producto`
    FOREIGN KEY (`i_id_proveedor`)
    REFERENCES `proyecto`.`proveedor` (`i_id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`tipo_usuario` (
  `i_id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(50) NOT NULL,
  `s_descripción` VARCHAR(300) NULL,
  PRIMARY KEY (`i_id_tipo_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`plantilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`plantilla` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`plantilla` (
  `i_id_plantilla` INT NOT NULL AUTO_INCREMENT,
  `s_nombre` VARCHAR(50) NOT NULL,
  `i_id_bar` INT NOT NULL,
  `i_id_grupo` INT NOT NULL,
  PRIMARY KEY (`i_id_plantilla`),
  INDEX `fk_i_id_bar_idx` (`i_id_bar` ASC),
  CONSTRAINT `fk_i_id_bar`
    FOREIGN KEY (`i_id_bar`)
    REFERENCES `proyecto`.`bar` (`i_id_bar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`plantilla_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`plantilla_productos` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`plantilla_productos` (
  `i_id_producto` INT NOT NULL,
  `i_id_plantilla` INT NOT NULL,
  `i_unidades` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`i_id_producto`, `i_id_plantilla`),
  INDEX `fk_i_id_plantilla_idx` (`i_id_plantilla` ASC),
  INDEX `fk_i_id_producto_idx` (`i_id_producto` ASC),
  CONSTRAINT `fk_i_id_plantilla`
    FOREIGN KEY (`i_id_plantilla`)
    REFERENCES `proyecto`.`plantilla` (`i_id_plantilla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_i_id_producto_plantilla_productos`
    FOREIGN KEY (`i_id_producto`)
    REFERENCES `proyecto`.`producto` (`i_id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`grupo_bar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`grupo_bar` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`grupo_bar` (
  `i_id_grupo` INT NOT NULL,
  `i_id_bar` INT NOT NULL,
  PRIMARY KEY (`i_id_grupo`, `i_id_bar`),
  INDEX `fk_i_id_grupo_idx` (`i_id_grupo` ASC),
  INDEX `fk_i_id_bar_idx` (`i_id_bar` ASC),
  CONSTRAINT `fk_i_id_grupo_grupo_bar`
    FOREIGN KEY (`i_id_grupo`)
    REFERENCES `proyecto`.`grupo` (`i_id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_bar_grupo_bar`
    FOREIGN KEY (`i_id_bar`)
    REFERENCES `proyecto`.`bar` (`i_id_bar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`grupo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`grupo_usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`grupo_usuario` (
  `i_id_grupo` INT NOT NULL,
  `i_id_usuario` INT NOT NULL,
  PRIMARY KEY (`i_id_grupo`, `i_id_usuario`),
  INDEX `fk_i_id_grupo_idx` (`i_id_grupo` ASC),
  INDEX `fk_i_id_usuario_idx` (`i_id_usuario` ASC),
  CONSTRAINT `fk_i_id_grupo_grupo_usuario`
    FOREIGN KEY (`i_id_grupo`)
    REFERENCES `proyecto`.`grupo` (`i_id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_usuario_grupo_usuario`
    FOREIGN KEY (`i_id_usuario`)
    REFERENCES `proyecto`.`usuario` (`i_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `proyecto`.`bar_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proyecto`.`bar_usuario` ;

CREATE TABLE IF NOT EXISTS `proyecto`.`bar_usuario` (
  `i_id_bar` INT NOT NULL,
  `i_id_usuario` INT NOT NULL,
  PRIMARY KEY (`i_id_bar`, `i_id_usuario`),
  INDEX `fk_i_id_usuario_idx` (`i_id_usuario` ASC),
  INDEX `fk_i_id_bar_idx` (`i_id_bar` ASC),
  CONSTRAINT `fk_i_id_bar_bar_usuario`
    FOREIGN KEY (`i_id_bar`)
    REFERENCES `proyecto`.`bar` (`i_id_bar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_i_id_usuario_bar_usuario`
    FOREIGN KEY (`i_id_usuario`)
    REFERENCES `proyecto`.`usuario` (`i_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


usuarioSET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
